language: python
python:
  - "3.7"
  - "3.8"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install coverage
  - pip install -r requirements.txt
script:
  - python setup.py test &
  - sleep 50
  - kill -2 %1
after_success:
  - coverage xml
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
