stages:
  - name: test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      language: python
      python: "3.7"
      script:
        - bash tests/test.sh
    - stage: test
      language: python
      python: "3.8"
      script:
        - bash tests/test.sh
    - stage: test
      language: python
      python: "nightly"
      script:
        - bash tests/test.sh
    - stage: deploy
      services:
        - docker
      env: L="Building manylinux1 on x86_64"
           DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
      script:
        - bash tests/build.sh travis
    - stage: deploy
      services:
        - docker
      env: L="Building manylinux2010 on x86_64"
           DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
      script:
        - bash tests/build.sh travis
    - stage: deploy
      services:
        - docker
      env: L="Building manylinux1 on i686"
           DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PLAT=manylinux1_i686
      script:
        - bash tests/build.sh travis
